FORMAT: 1A
HOST: https://api.starship.xyz

# Delivery API

Reserve and confirm robot deliveries. All requests need to include AccountSid and AuthToken headers

# Group Deliveries

## /deliveries

### Make delivery reservation [POST]

Returns 201 status code on success. Successful reservation is valid for 2 minutes.

Returns 400 on rejection, along with response body containing reason


 + no_robots
 + outside_hours
 + not_mapped
 + too_far
 + bad_request
 
+ Request (application/json)

     + Headers
     
            AccountSid: 370360ee-ca25-4b1a-9df7-1d625d601d37
            AuthToken: ac6f3815-c19d-467b-9768-41810f493c5c

    + Attributes

        + from (object, required) - Pickup location. Loading areas need to be configured before use
            + loadingarea: loading area id (string, required) 

        + to (object, required) - Address for delivery
            + address: Random Street 2 (string, required)
            + address2: Apt 64 (string, optional)
            + city: London (string, required)
            + zip: AR52 (string, required)
            + country: UK (string, required)
            
        + recipient (object, required)
            + name: Jane Doe (string, required)
            + phone: +441234567889 (string, required) - Mobile phone number
            
        + parcel (object, required)
            + description: Pizza (string, optional) - What's inside?
            + reference: CFG345 (string, required) - Order/delivery id in 
            
        + due (object, optional) - Delivery time slot
            + start: `2017-08-08T12:15:00Z` (string, required) - Start
            + end: `2017-08-08T12:30:00Z` (string, required) - End

            
+ Response 201

    + Body
    
            {
                "id": "5818bc832f00ee01e8402745",
                "status": "RESERVED"
            }
    
+ Response 400


    + Body
    
            {
                "code": "no_robots",
                "reason": "No available robots"
            }


   


    
## /deliveries/{id}

### Confirm delivery reservation [POST]

Confirm previously made reservation

+ Parameters
    + id - Id from response of reservation request
    
+ Request (application/json)

     + Headers
     
            AccountSid: 370360ee-ca25-4b1a-9df7-1d625d601d37
            AuthToken: ac6f3815-c19d-467b-9768-41810f493c5c

    + Attributes

        + action: CONFIRM (string, required) 

+ Response 200 (application/json)

    + Body

            {
                "id": "abc123",
                "status": "CONFIRMED"
            }
            
+ Response 400 (application/json)

    + Body

            {
                "reason": "Delivery not found or not RESERVED"
            }